version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
  chrome:
    image: selenium/node-chrome:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  dealsCpuChrome:
    image: suketdocker/deals
    depends_on:
        - chrome
        - firefox
    environment:
         - BROWSER=chrome
         - HUB_HOST=hub
    volumes:
         - ./output/newOutputChrome:/usr/share/dealsAutomation/target
         - /home/ec2-user/workspace/selenium_docker _runner/output/newOutputChrome/cucumber-reports/Cucumber.json:/usr/share/dealsAutomation/target/cucumber-reports/Cucumber.json
  dealsCpuFirefox:
    image: suketdocker/deals
    depends_on:
        - firefox
    environment:
         - BROWSER=firefox
         - HUB_HOST=hub
    volumes:
         - ./output/newOutputFirefox:/usr/share/dealsAutomation/target    